AWSTemplateFormatVersion: "2010-09-09"
Description: "Set up an S3 bucket used for S3 server access logging - (v1.0.0)"
Parameters:
  # General Configuration
  InfrastructureName:
    Type: "String"
    Description: "A name used to differentiate this infrastructure from other existing infrastructure."
  # Bucket Configuration
  BucketObjectExpirationInDays:
    Type: "Number"
    Description: "The default age of an object before it is automatically deleted from the bucket."
    Default: 180
Resources:
  ServerAccessLoggingBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "LogDeliveryWrite"
      BucketName: !Sub
      - "${AccountName}-${InfrastructureName}-server-access-logging-${AWS::Region}"
      - AccountName: "{{resolve:ssm:/account/name}}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
      LifecycleConfiguration:
        Rules:
        - Id: "DefaultObjectMaxAge"
          Prefix: ""
          Status: "Enabled"
          AbortIncompleteMultipartUpload:
            DaysAfterInitiation: !Ref BucketObjectExpirationInDays
          ExpirationInDays: !Ref BucketObjectExpirationInDays
          NoncurrentVersionExpirationInDays: !Ref BucketObjectExpirationInDays
      PublicAccessBlockConfiguration:
        # Block public access to buckets and objects granted through new access control lists (ACLs)
        BlockPublicAcls: false
        # Block public access to buckets and objects granted through any access control lists (ACLs)
        IgnorePublicAcls: false
        # Block public access to buckets and objects granted through new public bucket or access point policies
        BlockPublicPolicy: true
        # Block public and cross-account access to buckets and objects through any public bucket or access point policies
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: "Suspended"
      Tags:
      - Key: "Name"
        Value: !Ref "AWS::StackName"
      - Key: "application"
        Value: !Ref "AWS::StackName"
      - Key: "contact-email"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/contact-email}}"
      - Key: "customer"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/customer}}"
      - Key: "environment"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/environment}}"
      - Key: "team"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/team}}"
  ParamServerAccessLoggingBucketName:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: "text"
      Description: "The server access logging bucket name."
      Name: !Sub "/s3/${InfrastructureName}/bucket/logging/server-access/name"
      Tier: "Standard"
      Type: "String"
      Value: !Ref ServerAccessLoggingBucket
      Tags:
        Name: !Ref "AWS::StackName"
        application: !Ref "AWS::StackName"
        customer: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/customer}}"
        contact-email: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/contact-email}}"
        environment: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/environment}}"
        team: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/team}}"
  ParamServerAccessLoggingBucketArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: "text"
      Description: "The server access logging bucket ARN."
      Name: !Sub "/s3/${InfrastructureName}/bucket/logging/server-access/arn"
      Tier: "Standard"
      Type: "String"
      Value: !GetAtt ServerAccessLoggingBucket.Arn
      Tags:
        Name: !Ref "AWS::StackName"
        application: !Ref "AWS::StackName"
        customer: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/customer}}"
        contact-email: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/contact-email}}"
        environment: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/environment}}"
        team: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/team}}"
Outputs:
  ServerAccessLoggingBucketName:
    Description: "The bucket name."
    Value: !Ref ServerAccessLoggingBucket
    Export:
      Name: !Sub "${AWS::StackName}-ServerAccessLoggingBucketName"
  ServerAccessLoggingBucketArn:
    Description: "The bucket ARN."
    Value: !GetAtt ServerAccessLoggingBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ServerAccessLoggingBucketArn"
  ParamServerAccessLoggingBucketName:
    Description: "The server access logging bucket name SSM parameter."
    Value: !Ref ParamServerAccessLoggingBucketName
    Export:
      Name: !Sub "${AWS::StackName}-ParamServerAccessLoggingBucketName"
  ParamServerAccessLoggingBucketArn:
    Description: "The server access logging bucket ARN SSM parameter."
    Value: !Ref ParamServerAccessLoggingBucketArn
    Export:
      Name: !Sub "${AWS::StackName}-ParamServerAccessLoggingBucketArn"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - InfrastructureName
    - Label:
        default: "Bucket Configuration"
      Parameters:
      - BucketObjectExpirationInDays
    ParameterLabels:
      InfrastructureName:
        default: "Infrastructure Name:"
      BucketObjectExpirationInDays:
        default: "Default Object Expiration (In Days):"
