AWSTemplateFormatVersion: "2010-09-09" #The Format Version is optional.
Description: "Create an ACM certificate with Route53 DNS validation - (v1.0.0)."
Parameters:
  # General Configuration
  InfrastructureName:
    Type: "String"
    Description: "A name used to differentiate this infrastructure from other existing infrastructure."
  # Certificate Configuration
  PrimaryDomainName:
    Type: "String"
    Description: "Set the primary domain for this certificate (e.g. *.example.com)."
  SubjectAlternativeNames:
    Type: "String"
    Description: "Will this certificate have additional domains?  If so, add them to the following list."
    AllowedValues:
    - "Yes"
    - "No"
    Default: "No"
  SubjectAlternativeNamesList:
    Type: "CommaDelimitedList"
    Description: "Set a comma-delimited list of additional domains for this certificate (e.g. *.nonprod.example.com,*.prod.example.com)."
    Default: ""
  HostedZoneId:
    Type: "String"
    Description: "The Hosted Zone ID for the domain in Route53."
Conditions:
  SubjectAlternativeNames: !Equals [ !Ref SubjectAlternativeNames, "Yes" ]
Resources:
  Certificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      CertificateTransparencyLoggingPreference: "ENABLED"
      DomainName: !Ref PrimaryDomainName
      SubjectAlternativeNames: !If [ SubjectAlternativeNames, !Ref SubjectAlternativeNamesList, !Ref "AWS::NoValue" ] 
      ValidationMethod: "DNS"
      DomainValidationOptions:
      - DomainName: !Ref PrimaryDomainName
        HostedZoneId: !Ref HostedZoneId
      Tags:
      - Key: "Name"
        Value: !Ref "AWS::StackName"
      - Key: "application"
        Value: !Ref "AWS::StackName"
      - Key: "contact-email"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/contact-email}}"
      - Key: "customer"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/customer}}"
      - Key: "environment"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/environment}}"
      - Key: "team"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/team}}"
Outputs:
  CertificateArn:
    Description: "The ARN for the ACM certificate."
    Value: !Ref Certificate
    Export:
      Name: !Sub "${AWS::StackName}-CertificateArn"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - InfrastructureName
    - Label:
        default: "Certificate Configuration"
      Parameters:
      - PrimaryDomainName
      - SubjectAlternativeNames
      - SubjectAlternativeNamesList
      - HostedZoneId
    ParameterLabels:
      # General Configuration
      InfrastructureName:
        default: "Infrastructure Name:"
      # Certificate Configuration
      PrimaryDomainName:
        default: "Primary Domain Name:"
      SubjectAlternativeNames:
        default: "Additional Domain Names:"
      SubjectAlternativeNamesList:
        default: "Subject Alternative Names List:"
      HostedZoneId:
        default: "Route53 Hosted Zone ID:"