AWSTemplateFormatVersion: "2010-09-09"
Description: "Create CodeBuild GitHub Source Credential - (v1.0.0)"
Parameters:
  # General Configuration
  InfrastructureName:
    Type: "String"
    Description: "A name used to differentiate this infrastructure from other existing infrastructure."
Resources:
  CodeBuildSourceCredential:
    Type: "AWS::CodeBuild::SourceCredential"
    Properties:
      AuthType: "PERSONAL_ACCESS_TOKEN"
      ServerType: "GITHUB"
      Token: !Sub "{{resolve:secretsmanager:arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:account/${InfrastructureName}/github:SecretString:oAuthToken}}"
Outputs:
  CodeBuildSourceCredential:
    Description: "CodeBuild GitHub source credential."
    Value: !Ref CodeBuildSourceCredential
    Export:
      Name: !Sub "${AWS::StackName}-CodeBuildSourceCredential"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - InfrastructureName
    ParameterLabels:
      # General Configuration
      InfrastructureName:
        default: "Infrastructure Name:"